name: Check PR
on: pull_request

jobs:
  maven:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Run Checks
        run: mvn --batch-mode --no-transfer-progress --update-snapshots verify